
services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: osamu28
      DB_NAME: karismaacademy
      DB_PORT: 3306
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  admin:
    build: ./admin
    ports:
      - "5174:5174"
    volumes:
      - ./admin:/app
      - /app/node_modules
    depends_on:
      - backend

  db:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: karismaacademy
      MYSQL_USER: user
      MYSQL_PASSWORD: osamu28
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user", "-posamu28"]
      timeout: 5s
      retries: 10
      interval: 10s
      start_period: 30s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db

volumes:
  mysql-data: